### ISSUE TITLE
Running o1[t] & o1[t-1] & i1[t] = 0 || o1[t] = i1[t] becomes unsat after two consecutive 1 inputs.

### ISSUE THREAD

**Issue by hippie-cycling** [IDNI/tau-lang#8]
From the README example: o1[t] & o1[t-1] & i1[t] = 0 || o1[t] = i1[t]
"Which states that the current output, and the previous output, and the current input, has to be 0, or, the output has to equal the input."

Given two consecutive inputs of _1_, the program becomes unsat. Shouldn't the program output _1_ as o1[t] = i1[t]?

sat o1[t] & o1[t-1] & i1[t] = 0 || o1[t] = i1[t] is T.

Tau version: 0.7 (v0.7-alpha-30-g288acf6)

![Unsat of a TAU spec](https://github.com/user-attachments/assets/c00a3ec2-34f5-4651-b0a3-06f3596a2dbd)

**Comment by LEARNTAU** [comment]
I have the same result
OS: Ubuntu 22.04.5 LTS (64-bit)

![image](https://github.com/user-attachments/assets/c311f48f-8f4c-489f-b31f-720c8fa76afd)

**Comment by LEARNTAU** [comment]
I check it again and here is my results in Tau build-Release
![image](https://github.com/user-attachments/assets/72fc23a6-3f44-44d0-a0b6-beac8750607b)

Either I press T or F, the output gives me F. 

This is the sat, unsat and valid tests.
![image](https://github.com/user-attachments/assets/e7f30a5a-c034-4d90-a2cb-b70abfa6b996)

o1[t] & o1[t-1] & i1[t] = 0 || o1[t] = i1[t]
which states that at each point in time, either the conjunction of the current output with the previous output and with the current input, has to be 0, or, the output has to equal the input.  

here is my results in Tau executable in windows.
![image](https://github.com/user-attachments/assets/5b642863-5dfd-4636-9d54-c67c3f2445ff)

My interpretation is that once I entered Two successive input that is True, then it will give me (Error) empty program. My analysis is that when two successive inputs are True, then T & T & T = 0 , this will result for the program to be 0. 

Is my conclusion correct to say that when result is 0, it will be empty program?

**Comment by LuccaT95** [comment]
This issue is fixed on the master branch. The following behaviour [LEARNTAU](https://github.com/LEARNTAU) also mentioned when running the Tau formula `o1[t] & o1[t-1] & i1[t] = 0 || o1[t] = i1[t]` is the expected one ( I will explain below why)

![Bildschirmfoto_20241219_110334](https://github.com/user-attachments/assets/ab36ae59-165a-41e0-952f-c558e7213671)

First of all, since the formula is a disjunction, in each step during execution either `o1[t] & o1[t-1] & i1[t] = 0` or `o1[t] = i1[t]` must be satisfied. In the output you see, Tau executes `o1[t] & o1[t-1] & i1[t] = 0` in each step.
In the initial step `t` is set to 1 leading to the formula `o1[1] & o1[0] & i1[1] = 0`.
Note that `o1[0]` is not restricted by this formula. Therefore, in execution step 0 Tau will assign `0` to it.
As a result, we have `o1[1] & 0 & i1[1] = 0` as specification for the execution step 1. But note that `o1[1] & 0 & i1[1] ` is equivalent to `0`. Therefore, we get `0 = 0` during execution step 1. Hence, the output `o1[1]` does not depend on the input and can be set to `0`.
We can now check that those assignments indeed satisfy the original formula for `t = 1` :
`o1[t] & o1[t-1] & i1[t] = 0 || o1[t] = i1[t]` becomes `0 & 0 & i1[1] = 0 || 0 = i1[t]'` which is equivalent to `T`. 
You can check that the output from Tau satisfies the original formula in this fashion for any given `t`.

Maybe just as a closing note, if the program does not ask for input in a particular step, you see a blank line and just need to press ENTER to go to the next step.
If the program asks for input, you will see something of the form `i1[n] := `.

Have a great day!
